site_name: DBReport
site_description: RealBasic/Xojo component for reports website
site_author: Bernardo Monsalve
copyright: 2017Â© Bernardo Monsalve
pages:
- Home: index.md
- Classes: classes.md
- About:
    - Release Notes: release.md
    - License: license.md

extra_css:
    - css/vs.css